### ISSUE TITLE
Help implementing ember-cli-summernote add-on in existing app

### ISSUE THREAD

**Issue by jvenator** [vsymguysung/ember-cli-summernote#1]
Hi there. Thanks for putting this together! I'm attempting to implement it in a small ember-cli project of mine that I'm using to learn, experiment and share with others. I am new to ember and am having difficulty using this add-on. Would you be will to take a look at my implementation and see where I'm going wrong?

Here's repo branch where I'm attempting to add ember-cli-summernote - https://github.com/jvenator/interest-bucket/tree/summernote

I did the following things so far...

* `$ npm install ember-cli-summernote --save-dev`
* `$ ember g ember-cli-summernote`
* ran `npm install && bower install`
* updated `Brocfile.js` and confirmed that `bower_components` includes assets for bootstrap and fontawesome
* created a route for `/summernote`
* created a template at `templates/summernote.hbs` and dropped in your example markup

Do you see anything I might be missing or doing incorrectly? Thanks for your time.

*Also, I'm happy to contribute some additional documentation/explanation to your repot based on what I learn.*

**Comment by vsymguysung** [comment]
@jvenator, I found a bug where the addon handles the app.options that you set up in the Brocfile.js.
So now ember-cli-summernote is version 0.1.10, please try this version and you may also want to setup the ```contentSecurityPolicy``` in the ```config/environment.js``` with the following 

```
module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'interest-bucket',
    firebase_instance: process.env.FIREBASE_APP_NAME,
    environment: environment,
    baseURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      }
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    },
    contentSecurityPolicy: {
      'img-src': "'self' data:",
      'style-src':"'self' 'unsafe-inline'"
    },
  };
```
Thanks for letting me have a chance to correct this and you're more than welcome to join and contribute to this project.

**Comment by jvenator** [comment]
It works! And thanks for the heads up regarding the `contentSecurityPolicy`.

There is one more thing I am trying to do based on your demo app, which is to render the wysiwyg results below the editor area. I did the following inside `summernote.hbs` for route `/summernote`.

```handlebars
{{summer-note height=200 btnSize=bs-sm content=postContent}}

<div class='wysiwyg-preview'>
	<pre>
		{{postContent}}
	</pre>
</div>
```

It appears to be escaping the HTML and not rendering it properly. Anything I'm missing in my configuration elsewhere? I looked in your `dummy.js` file, but it's difficult to understand. It seems that you are setting `unescaped: true`, which I assume has something to do with `Handlebars.SafeString`.

Here's a screenshot of the output:

![screenshot]
(http://cl.ly/image/3y113O0e053l/Image%202015-01-01%20at%209.06.50%20PM.png)

**Comment by vsymguysung** [comment]
You may want to try ```{{{postContent}}}``` instead of ```{{postContent}}```.

**Comment by jvenator** [comment]
Much appreciated. Crazy that my googling of "handlebars escape html" didn't turn that up as one of the first results. Once I've messed around with it a little more to understand it better I'll submit a PR for some example explanation in the README. You can accept if you think it's of value.

**Comment by vsymguysung** [comment]
Sure, please submit a PR, I will review it. 
Thanks for your contribution.
