### ISSUE TITLE
Binding 'backend' content changes to the component

### ISSUE THREAD

**Issue by shopapps** [vsymguysung/ember-cli-summernote#11]
Hi,

I don't know if this is the correct method, but I had an issue where I was updating the backend model that was providing the html content, but this change was not being reflected in the WYSIWYG output.

To fix this I had two options:
### Option 1

Edit the summer-note src **ember-cli-summernote/addon/components/summer-note.js**  and around line 72 (just above **doUpdate**)  I inserted:

```
observeContent: Ember.observer('content', function(){
   this.$('.note-editable').html(this.get('content'));
}),
```
### Option 2

Extend the component (which mostly,  should be upgrade proof).  Create a new component file, in my case it was in **app/pods/components/summer-note/component.js** 

```
import Ember from 'ember';
import SummerNoteComponent from 'ember-cli-summernote/components/summer-note';

export default SummerNoteComponent.extend({
  observeContent: Ember.observer('content', function(){
    this.$('.note-editable').html(this.get('content'));
  }),
});
```

I just thought I would put this up here in case others had a similar problem...

**Comment by shopapps** [comment]
doh...  I just realised doing either of the above makes it very difficult to actually edit the WYSIWYG box as it keeps reloading every time you type...  hmm back to the drawing board..

**Comment by shopapps** [comment]
so in the end I removed all of the above and instead, at the point where I change the model I added a line:

    Ember.$('.note-editable').html(model.get('bodyHTML')) ;

which isn't ideal as the model and wysiwyg content are 'out of sync' (or at least disconnected) but does the job in practical terms.

**Comment by vsymguysung** [comment]
Thank you for being patient. As of version `1.1.0`,  I finally resolved this by following `DDAU` pattern. Now you can use `content` property as readonly and use `onContentChange` action for updated contents.
