### ISSUE TITLE
does not provide summernote callback functionality

### ISSUE THREAD

**Issue by zanethomas** [vsymguysung/ember-cli-summernote#14]
callbacks such as http://summernote.org/deep-dive/#onimageupload can be quite useful

**Comment by vsymguysung** [comment]
Hi @zanethomas ! Thanks for your comment. I am going to definitely consider it but  now I am in for other projects so it's not going to happen near future. If possible, you could make a pull request.

**Comment by hxbkx** [comment]
I made a pull request about this issue

**Comment by vsymguysung** [comment]
It's supported as of version 1.0.0.  Thanks much!  @hxbkx
