### ISSUE TITLE
lang support

### ISSUE THREAD

**Issue by acerov** [vsymguysung/ember-cli-summernote#19]
Hi,

Thank you for addon and one quick question:

How to change language, I tried lang="hr-HR" but no luck.

**Comment by vsymguysung** [comment]
Unfortunately, it's not supported yet. I assume that you are considering "dynamic language support" which means each summernote instance could have a different language.  If that is the case, the addon should either include all lang js files (total 203 KB) or find out selectively including a `lang js` file, but I don't now how I could include a `lang js` file dynamically for each instance.  If the addon only support static fixed language support through the `environment.js`, then I could consider adding `lang` attribute later. I am open to any suggestion and pull request so feel free to let me know. Thanks.

**Comment by acerov** [comment]
Static will be fine for start but of course dynamic would be great, I am completely new to library so dont have any suggestions for good aproach.

So please add `lang` attribute

Thnx

**Comment by vsymguysung** [comment]
It's supported as of v1.0.0. Thanks.
