### ISSUE TITLE
Problems when shown in a modal.

### ISSUE THREAD

**Issue by NeilAllen** [vsymguysung/ember-cli-summernote#20]
If the component is show inside a modal the Help page is displayed & clicking the X closes the whole thing; clicking elsewhere closes summernote but leaves the overlay.

![capture](https://cloud.githubusercontent.com/assets/13977890/15397781/48e6075e-1dd9-11e6-9b4e-39a8bc1fd06f.PNG)

Like much of the work on npmjs incomplete & buggy; surely it only looks good on a CV if it's any good

**Comment by vsymguysung** [comment]
I upgraded the summernote to version 0.8.3. Could you please try it to see if you have the same issue with it ? If you can set up the test repo, that would be greatly helpful. Thanks.
