### ISSUE TITLE
Attempting to import font files from summernote dist directory that doesn't exist

### ISSUE THREAD

**Issue by billdami** [vsymguysung/ember-cli-summernote#23]
After installing ember-cli-summernote and running the blueprint to install the bower dependencies, I am receiving an error on ember build/serve:

```
Error: ENOENT: no such file or directory, scandir '/project-path/tmp/funnel-input_base_path-kcgi7jIX.tmp/bower_components/summernote/dist/font/'
```

I noticed the addon's index.js is attempting to import the following:
```
app.import(path.join(summernotePath, 'font/summernote.eot'), { destDir: 'assets/font' });
app.import(path.join(summernotePath, 'font/summernote.ttf'), { destDir: 'assets/font' });
app.import(path.join(summernotePath, 'font/summernote.woff'), { destDir: 'assets/font' });
```

However, those files do not appear to exist in v0.7.0 of summernote in /bower_components/summernote/dist.

**Comment by billdami** [comment]
So the cause of this is that while the addon has a dependency on summernote v0.8.3 (which does have the font files), the blueprint installs version 0.7.0:

```
return that.addBowerPackageToProject('summernote', "~0.7.0");
```

If this is updated to the latest summernote version too, I think this issue should be resolved.

**Comment by billdami** [comment]
Note that it seems like the FontAwesome dependency has been removed from summernote, so looks like the importing of the fontawesome font files could be removed from this addon too.

**Comment by vsymguysung** [comment]
Thank you for your feedback. I will be able to take care of this by next week and if possible, pull request are always welcomed. 👍

**Comment by vsymguysung** [comment]
As of version 1.3.0, the dependency mismatch in the blueprint has been fixed and `Fontawesome` dependency has also been removed. Thanks again @billdami.
