### ISSUE TITLE
Fastboot Support

### ISSUE THREAD

**Issue by billdami** [vsymguysung/ember-cli-summernote#24]
When attempting to use the addon with a fastboot enabled app, requests fail due to the summernote.min.js javascript generating errors, since its not meant to run on the server.

This should be a fairly straightforward fix I believe, by adjusting the index.js's import logic as follows:

```javascript
if (config.importBootstrapJS && !process.env.EMBER_CLI_FASTBOOT) {
  app.import(path.join(bootstrapPath, '/js/bootstrap.min.js'));
}

//...

if (!process.env.EMBER_CLI_FASTBOOT) {
  app.import(path.join(summernotePath, 'summernote.min.js'));
}
//import the rest of the dependencies as normal...
```

**Comment by vsymguysung** [comment]
As of the version 1.3.0, `fastboot` support has been added. Thanks again @billdami.
