### ISSUE TITLE
Problems re-rendering

### ISSUE THREAD

**Issue by seocahill** [vsymguysung/ember-cli-summernote#8]
Thanks for the add-on.

Say we have a list of items and clicking on an item renders a child view with the summernote component and the item's content passed in.

I had to do the following to update the content within the component:

```
 setup: Ember.on('didRender', function() {
    $('#editor').summernote();
  }),
 update: Ember.on('didUpdate', function() {
   $('".note-editable').html(this.get("content"));
 })
```

**Comment by seocahill** [comment]
I've messed around with this a bit an it's quite a tricky fix (for me :)).

If anyone else has this problem a hacky way to handle this is to update the textarea's code using the afterModal hook in the item's route.

**Comment by shopapps** [comment]
I'm not sure if it's quite the same thing, but I fixed a similar sounding issue, which I have explained here: https://github.com/vsymguysung/ember-cli-summernote/issues/11

**Comment by vsymguysung** [comment]
Thank you for being patient. As of version `1.1.0`,  I finally resolved this by following `DDAU` pattern. Now you can use `content` property as readonly and use `onContentChange` action for updated contents.
